{
  "uid" : "4b4757e66a1912dae1a509f688f20b0f",
  "children" : [ {
    "name" : "Test defects",
    "children" : [ {
      "name" : "dataclay.exceptions.exceptions.DataClayException: b'\\n--------------------------------------------------------------------------------------------------------------------------------------------------\\nError Stack: \\n--------------------------------------------------------------------------------------------------------------------------------------------------\\nServer Traceback (most recent call last):\\n  File \"/home/dataclayusr/dataclay/dataclay_venv/lib/python3.7/site-packages/dataClay-2.7-py3.7.egg/dataclay/communication/grpc/server/ExecutionEnvironmentService.py\", line 331, in newReplica\\n    request.recursive)\\n\\n--------------------------------------------------------------------------------------------------------------------------------------------------'\n",
      "children" : [ {
        "name" : "replica from replica",
        "uid" : "f8d8d116d655285a",
        "parentUid" : "a1770f2bf8339740295fe87822e2482b",
        "status" : "broken",
        "time" : {
          "start" : 1639640176811,
          "stop" : 1639640397087,
          "duration" : 220276
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ "None", "py37", "Linux", "linux/amd64", "slim" ]
      } ],
      "uid" : "a1770f2bf8339740295fe87822e2482b"
    } ],
    "uid" : "bdbf199525818fae7a8651db9eafe741"
  } ],
  "name" : "categories"
}